### ISSUE TITLE
New releases tracking

### ISSUE THREAD

**Issue by PaulLeCam** [3box/3box#1263]
Libraries

- [x] `dids` v1 + `key-did-provider-ed25519`
- [x] Ceramic with `key` method support
- [x] `idx-constants` with new IDs and breaking change: `cryptoAccountLinks` -> `cryptoAccounts` renaming
- [x] `idx-tools` with latest Ceramic support, breaking changes:
  - [x] `cryptoAccountLinks` -> `cryptoAccounts` renaming
  - [x] removed constants
- [x] `idx` with latest Ceramic support, latest IDX tools and constants and added IDX document creation
  - [x] Updated docs with new Ceramic package names
  - [ ] Document lazy creation of IDX document
- [x] `identity-wallet` renamed to `3id-did-provider` with latest Ceramic support
- [x] `3id-connect` with latest Ceramic support, latest `identity-wallet` and IDX constants changes
- [ ] `idx-web` with latest `idx` and `3id-connect`

Tutorials and other projects

- [x] `idx-demo-app` + tutorial
- [x] Web playground
- [x] SelfID

Open questions:
- [x] Any other breaking change or dependency for `identity-wallet`?
- [ ] Shall we drop `idx-web`? It makes it harder to create new packages on top of IDX, such as a `react-idx` that couldn't work server-side if built on top of `idx-web`.

**Comment by oed** [comment]
Thanks for creating this.
One other change:
* `identity-wallet` package name change -> `3id-did-provider`

**Comment by PaulLeCam** [comment]
Thanks! I updated it
