### ISSUE TITLE
Host November 3Box Community Call

### ISSUE THREAD

**Issue by michaelsena** [3box/3box#761]
QA session

## Preparation

- [x]  Pick themes
- [x]  Invite external speakers
- [x]  Create initial agenda
- [x]  Decide date and time
- [x]  Add dates for call and emails to events calendar on Notion

### Initial invite

approx 2 weeks before

- [x]  Create mailchimp list and signup form
- [x]  Tweet invitation from 3Box
- [x]  Invite Consensys members
- [x]  Share on 3Box Discord
- [x]  Ask external speakers to share invitation

### Leadup

- [x]  Finalise agenda, send to team and external speakers (approx 3 before)
- [x]  3Box share on personal twitter/social media (Linkedin?)
- [x]  Email last chance invite (day before)
- [x]  Last chance tweet and discord post
- [x]  Pre sink call with team (same day or day before)
- [x]  mailchimp tags to participants
